/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI_Stegano_Kripto;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;

/**
 *
 * @author ACER
 */
public class Enkripsi extends javax.swing.JFrame {
    private String coverpath;
    public BuatStegano buat;

    public Enkripsi() {
        initComponents();
        Tchipper.setEditable(false);
        Tpesan.requestFocus();
      
    }
    
    private void enkripsi(){
        String key  = TKeykrip.getText();
        String plainttext = (key.length()+key+Tpesan.getText());
        String out = "";
        
        for (int i = 0; i < plainttext.length(); i++) {
            int index = plainttext.charAt(i);
            char s = (char)(index+1);
            out = out+ String.valueOf(s);
        }
        Tchipper.setText(out);
        Tpesan.setText("");
        TKeykrip.setText("");
        Tpesan.requestFocus();
    }
    
    private File pilihfile(){
        
        JFileChooser pilih = new JFileChooser();
        int dapat = pilih.showDialog(null, null);
        if (dapat == JFileChooser.APPROVE_OPTION) {
            File direktori = pilih.getSelectedFile();
            return direktori;
        }
        return null;
    }
    
    private void sisip(){
       String alamatFileCover=this.Talamatfile.getText();
        String alamatFolder="";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Pilih folder destinasi file!");
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            alamatFolder = selectedFile.getAbsolutePath();
            if(alamatFileCover != null && alamatFolder != ""){
                try {
                    BufferedImage cover = ImageIO.read(new File(alamatFileCover));
                    this.buat = new BuatStegano(cover);
                    
                    if(this.buat.sisipPesan(this.Tchipper.getText(), alamatFolder)){
                        this.Lstatus.setText("<Berhasil disimpan di: " + alamatFolder + "/Stegofile.bmp>");
                    }else{
                        this.Lstatus.setText("<Gagal>");

                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(Enkripsi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
}
    
    private void bersih(){
         Talamatfile.setText("");
         Tchipper.setText("");
         lcover.setIcon(null);
         TKeykrip.setText("");
         Tpesan.setText("");
     }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        MinimSize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Tchipper = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Bfilechoser = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        lcover = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Talamatfile = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        Lstatus = new javax.swing.JLabel();
        Bencode = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Bubahtext = new javax.swing.JButton();
        TKeykrip = new javax.swing.JPasswordField();
        Tpesan = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        MinimSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MinimSize.setForeground(new java.awt.Color(255, 255, 255));
        MinimSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimSize.setText("-");
        MinimSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimSizeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Encrypt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(MinimSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(MinimSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Masukan Pesan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ChipperText");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        Tchipper.setBackground(new java.awt.Color(0, 51, 102));
        Tchipper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tchipper.setForeground(new java.awt.Color(255, 255, 255));
        Tchipper.setBorder(null);
        Tchipper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TchipperActionPerformed(evt);
            }
        });
        jPanel2.add(Tchipper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Encode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bfilechoser.setBackground(new java.awt.Color(0, 51, 102));
        Bfilechoser.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        Bfilechoser.setForeground(new java.awt.Color(255, 255, 255));
        Bfilechoser.setText("Browse");
        Bfilechoser.setBorder(null);
        Bfilechoser.setContentAreaFilled(false);
        Bfilechoser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bfilechoser.setOpaque(true);
        Bfilechoser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfilechoserActionPerformed(evt);
            }
        });
        jPanel3.add(Bfilechoser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 70, 20));

        Breset.setBackground(new java.awt.Color(0, 51, 102));
        Breset.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        Breset.setForeground(new java.awt.Color(255, 255, 255));
        Breset.setText("Reset");
        Breset.setBorder(null);
        Breset.setContentAreaFilled(false);
        Breset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Breset.setOpaque(true);
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        jPanel3.add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 240, 30));

        lcover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lcover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lcover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 480, 210));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Preview gambar");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        Talamatfile.setEditable(false);
        Talamatfile.setBackground(new java.awt.Color(0, 51, 102));
        Talamatfile.setForeground(new java.awt.Color(255, 255, 255));
        Talamatfile.setBorder(null);
        jPanel3.add(Talamatfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 400, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 153));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 10));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pilih Cover");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Lstatus.setForeground(new java.awt.Color(255, 255, 255));
        Lstatus.setText("Status Penyisipan");
        jPanel3.add(Lstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 210, 20));

        Bencode.setBackground(new java.awt.Color(0, 51, 102));
        Bencode.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        Bencode.setForeground(new java.awt.Color(255, 255, 255));
        Bencode.setText("Embeded");
        Bencode.setBorder(null);
        Bencode.setContentAreaFilled(false);
        Bencode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bencode.setOpaque(true);
        Bencode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BencodeActionPerformed(evt);
            }
        });
        jPanel3.add(Bencode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 420));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 500, 10));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukan Key");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Bubahtext.setBackground(new java.awt.Color(0, 51, 102));
        Bubahtext.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        Bubahtext.setForeground(new java.awt.Color(255, 255, 255));
        Bubahtext.setText("Ubah Text");
        Bubahtext.setBorder(null);
        Bubahtext.setContentAreaFilled(false);
        Bubahtext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bubahtext.setOpaque(true);
        Bubahtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubahtextActionPerformed(evt);
            }
        });
        jPanel2.add(Bubahtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 500, 20));

        TKeykrip.setBackground(new java.awt.Color(0, 51, 102));
        TKeykrip.setForeground(new java.awt.Color(255, 255, 255));
        TKeykrip.setBorder(null);
        jPanel2.add(TKeykrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 500, -1));

        Tpesan.setBackground(new java.awt.Color(0, 51, 102));
        Tpesan.setForeground(new java.awt.Color(255, 255, 255));
        Tpesan.setBorder(null);
        jPanel2.add(Tpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 51, 153));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 500, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 720));

        setSize(new java.awt.Dimension(520, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        Menu_Utama utama = new Menu_Utama();
        utama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void MinimSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimSizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_MinimSizeMouseClicked

    private void BfilechoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfilechoserActionPerformed
        // TODO add your handling code here:
        try {
            File file = pilihfile();
            lcover.setIcon(new ImageIcon(ImageIO.read(new File(file.getPath()))));
            coverpath = file.getPath();
            this.Talamatfile.setText(coverpath);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            
        }
    }//GEN-LAST:event_BfilechoserActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
       bersih();
    }//GEN-LAST:event_BresetActionPerformed

    private void BubahtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubahtextActionPerformed
        // TODO add your handling code here:
        enkripsi();
    }//GEN-LAST:event_BubahtextActionPerformed

    private void TchipperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TchipperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TchipperActionPerformed
int x,y;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void BencodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BencodeActionPerformed
        // TODO add your handling code here:
        sisip();
    }//GEN-LAST:event_BencodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bencode;
    private javax.swing.JButton Bfilechoser;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Bubahtext;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel MinimSize;
    private javax.swing.JPasswordField TKeykrip;
    private javax.swing.JTextField Talamatfile;
    private javax.swing.JTextField Tchipper;
    private javax.swing.JTextField Tpesan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lcover;
    // End of variables declaration//GEN-END:variables

}
