/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI_Stegano_Kripto;

/**
 *
 * @author ACER
 */
public class Menu_Utama extends javax.swing.JFrame {
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bdekrip = new javax.swing.JButton();
        Benkripsi1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        MinimSize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bdekrip.setBackground(new java.awt.Color(0, 0, 0));
        Bdekrip.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        Bdekrip.setForeground(new java.awt.Color(255, 255, 255));
        Bdekrip.setText("Dekripsi");
        Bdekrip.setBorder(null);
        Bdekrip.setContentAreaFilled(false);
        Bdekrip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bdekrip.setOpaque(true);
        Bdekrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdekripActionPerformed(evt);
            }
        });
        getContentPane().add(Bdekrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 210, 50));

        Benkripsi1.setBackground(new java.awt.Color(0, 0, 0));
        Benkripsi1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        Benkripsi1.setForeground(new java.awt.Color(255, 255, 255));
        Benkripsi1.setText("Enkripsi");
        Benkripsi1.setBorder(null);
        Benkripsi1.setContentAreaFilled(false);
        Benkripsi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Benkripsi1.setOpaque(true);
        Benkripsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Benkripsi1ActionPerformed(evt);
            }
        });
        getContentPane().add(Benkripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        MinimSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MinimSize.setForeground(new java.awt.Color(255, 255, 255));
        MinimSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimSize.setText("-");
        MinimSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimSizeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Utama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(MinimSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(MinimSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/logo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bg.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        setSize(new java.awt.Dimension(400, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BdekripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdekripActionPerformed
        // TODO add your handling code here:
        Dekripsi dek = new Dekripsi();
        dek.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BdekripActionPerformed

    private void Benkripsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Benkripsi1ActionPerformed
        // TODO add your handling code here:
        Enkripsi en = new Enkripsi();
        en.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Benkripsi1ActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void MinimSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimSizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_MinimSizeMouseClicked
int x,y;
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdekrip;
    private javax.swing.JButton Benkripsi1;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel MinimSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
